### ISSUE TITLE
name 'build_word_vectors' is not defined

### ISSUE THREAD

**Issue by staywithme23** [BarakOshri/TextualReconstructor#3]
1. name 'build_word_vectors' is not defined
   in file train.py, line 19.
2. Is the vector.6B.200d.txt relates to glove.6B.200d.txt?

**Comment by transfluxus** [comment]
got the same error.
did you fix it and can you tell me how? :)

**Comment by transfluxus** [comment]
ok I just supposed it might be 'build' in  data_processing/wiki_to_vectors.py and it is supposed to be at http://nlp.stanford.edu/projects/glove/... but http://nlp.stanford.edu is down

**Comment by transfluxus** [comment]
alright
next one:
`Traceback (most recent call last):                                                                   │ramin@lyrik:~ GPU:: 0 % 💻  cd projects/ECO/src/tests/
  File "train.py", line 19, in <module>                                                              │ramin@lyrik:~/projects/ECO/src/tests GPU:: 0 % 💻  ls
    glove_mat, glove_vocab = build(word_vector_file) # Matrix of shared theano tensor vectors        │grammar.py
  File "data_processing/wiki_to_vectors.py", line 20, in build                                       │ramin@lyrik:~/projects/ECO/src/tests GPU:: 0 % 💻  python grammar.py "this were cool"                
    mat.append(np.array(map(float, line[1: ])))                                                      │  File "grammar.py", line 13
ValueError: invalid literal for float(): 0.17651 0.29208 -0.0020768 -0.37523 0.0049139 0.23979 -0.288│    return
93 -0.014643 -0.10993 0.15592 0.20627 0.47675 0.099907 -0.14058 0.21114 0.12126 -0.31831 -0.089433 -0│SyntaxError: 'return' outside function
.090553 -0.31962 0.21319 2.4844 -0.0775     `

**Comment by transfluxus** [comment]
next one:
`Building word vectors
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    glove_mat, glove_vocab = build(word_vector_file) # Matrix of shared theano tensor vectors
  File "data_processing/wiki_to_vectors.py", line 20, in build
    mat.append(np.array(map(float, line[1: ])))
ValueError: invalid literal for float(): 0.17651 0.29208 -0.0020768 -0.37523 0.0049139 0.23979 -0.28893 -0.014643 -0.10993 0.15592 0.20627 0.47675 0.099907 -0.14058 0.21114 0.12126 -0.31831 -0.089433 -0.090553 -0.31962 0.21319 2.4844 -0.0775`

**Comment by s7kjd3** [comment]
@transfluxus I met the same question  "ValueError: invalid literal for float(): 0.013441 0.23682 -0.16899 0.40951 0.63812 0.47709 -0.42852 -0.55641 -0.364 -0.23938 0.13001 -0.063734 -0.39575 -0.48162 0.23291 0.090201 -0.13324 0.078639 -0.41634 -0.15428 0.10068 0.48891 0.31226 -0.
", did you solve that?
